import {catalogTracks} from '../music/catalog-tracks';
import {recommendationJson,recommendationPlaylist,readRecommendationCache,saveRecommendationCache} from '../recommendation-data';
﻿import {sceneCategories,moodCategories,genreCategories,type CuratedFeed,type CuratedPlaylist} from '../../curated-types';
import type {Mix,Song} from '../../music-types';
const categories=[...new Set([...sceneCategories,...moodCategories,...genreCategories])];
let cache:CuratedFeed|undefined,pending:Promise<CuratedFeed>|undefined;const details=new Map<string,{until:number;mix:Mix}>();
const groupTimes=new Map<string,number>();
function cover(raw:unknown){try{const u=new URL(String(raw).replace(/^http:/,'https:'));if(!/^p\d+\.music\.126\.net$/.test(u.hostname))return '';u.search='';return u.href+'?param=600y600'}catch{return ''}}
async function list(category:string,signal:AbortSignal){const path='/api/playlist/list?'+new URLSearchParams({cat:category,order:'hot',limit:'8',offset:'0'});const j=await recommendationJson([path,path+'&total=false'],j=>j.code===200&&Array.isArray(j.playlists)&&j.playlists.length>0,signal);return j.playlists.map((p:any):CuratedPlaylist=>({id:String(p.id),title:String(p.name),cover:cover(p.coverImgUrl),count:Number(p.trackCount)||0,plays:Number(p.playCount)||0,updated:Number(p.trackUpdateTime||p.updateTime||p.createTime)||0,category}))}
async function refresh(force=false):Promise<CuratedFeed>{
 const groups:Record<string,CuratedPlaylist[]>={...cache?.groups},failed=new Set<string>();
 const tasks=categories.filter(cat=>force||!groups[cat]?.length||Date.now()-(groupTimes.get(cat)||0)>900000);
 const deadline=AbortSignal.timeout(22000);
 await Promise.all(Array.from({length:4},async()=>{while(tasks.length){const cat=tasks.shift()!;try{groups[cat]=await list(cat,deadline);groupTimes.set(cat,Date.now())}catch{failed.add(cat);groups[cat]??=[]}}}));
 const newest=[...new Map(Object.values(groups).flat().map(p=>[p.id,p])).values()].filter(p=>p.updated>0).sort((a,b)=>b.updated-a.updated).slice(0,8);
 if(!Object.values(groups).some(a=>a.length))throw Error('精选歌单暂不可用');
 return {groups,newest,updated:Date.now(),stale:failed.size>0,missing:categories.filter(cat=>!groups[cat]?.length)};
}
export async function GET(request:Request){try{const id=new URL(request.url).searchParams.get('id');if(id){if(!/^\d{1,18}$/.test(id))return Response.json({error:'歌单编号无效'},{status:400});const hit=details.get(id);if(hit&&hit.until>Date.now())return Response.json(hit.mix);const j=await recommendationPlaylist(id,500,request.signal);const p=j.playlist;if(!p)throw Error('此歌单已失效或不可访问');let tracks=p.tracks||[];const ids=(p.trackIds||[]).slice(0,500).map((t:any)=>t.id);if(ids.length>tracks.length){const collected:any[]=[...tracks],present=new Set(tracks.map((t:any)=>String(t.id))),missing=ids.map(String).filter((id:string)=>!present.has(id)),batches:string[][]=[];for(let i=0;i<missing.length;i+=200)batches.push(missing.slice(i,i+200));for(const batch of await Promise.all(batches.map(ids=>catalogTracks(ids,request.signal))))collected.push(...batch);const map=new Map(collected.map(t=>[String(t.id),t]));tracks=ids.map((id:number)=>map.get(String(id))).filter(Boolean)}const songs:Song[]=tracks.map((s:any)=>{const ms=Number(s.dt||s.duration)||0;return {id:'wy_'+s.id,provider:'at38',title:s.name,artist:(s.ar||s.artists||[]).map((a:any)=>a.name).join(' / '),album:(s.al||s.album)?.name||'',cover:cover((s.al||s.album)?.picUrl),durationMs:ms,duration:ms?Math.floor(ms/60000)+':'+String(Math.floor(ms/1000)%60).padStart(2,'0'):''}});const mix:Mix={id,title:p.name,cover:cover(p.coverImgUrl),description:String(p.description||'').slice(0,240)+(p.trackCount>songs.length?` · 当前读取 ${songs.length} / ${p.trackCount} 首`:''),songs,tone:'green',updated:p.updateTime||Date.now()};if(details.size>=60)details.delete(details.keys().next().value!);details.set(id,{until:Date.now()+300000,mix});return Response.json(mix)}if(!cache){const saved=await readRecommendationCache<{data:CuratedFeed;times:[string,number][]}>('curated');if(saved){cache=saved.data;for(const [cat,at] of saved.times)groupTimes.set(cat,at)}}const force=new URL(request.url).searchParams.get('refresh')==='1';if(!cache||force||Date.now()-cache.updated>(cache.stale?30000:900000)){pending??=refresh(force&&!cache?.stale).then(async d=>{cache=d;await saveRecommendationCache('curated',{data:d,times:[...groupTimes]});return d}).finally(()=>{pending=undefined});await pending}return Response.json(cache,{headers:{'Cache-Control':'no-store'}})}catch{return cache&&!new URL(request.url).searchParams.has('id')?Response.json({...cache,stale:true}):Response.json({error:'精选歌单暂时无法加载，请稍后重试'},{status:503})}}

