'use client';
import type {PlaylistSync} from './playlist-import/sync-model';
import {importBatch} from './playlist-import/upload';
import {accountRequest} from './account-request';
import {SsoButtons} from './site-features';
import {LOGIN_CHALLENGE_REQUIRED,REGISTER_CHALLENGE_REQUIRED} from './auth-policy';
import {TurnstileChallenge} from './turnstile-challenge';
import {createContext,useContext,useEffect,useRef,useState} from 'react';
import {Plus} from 'lucide-react';

import {updateSearches} from './search-history';
import type {Song} from './music-types';
type Library={searches:string[];favorites:Song[];recent:Song[];playlists:{id:string;name:string;songs:Song[];sync?:PlaylistSync}[]};const empty=():Library=>({searches:[],favorites:[],recent:[],playlists:[]});
export const AccountContext=createContext<(s:Song)=>void>(()=>{});
export function AddToPlaylist({song}:{song:Song}){const add=useContext(AccountContext);return <button className="icon-btn add-to-playlist" title="加入歌单" aria-label="加入歌单" onClick={()=>add(song)}><Plus size={24} strokeWidth={2}/></button>}
export function useAccount(){const [user,setUser]=useState<{id:string;name:string;username:string}|null>(null),[library,setLibrary]=useState<Library>(empty),[ready,setReady]=useState(false),[error,setError]=useState(''),[open,setOpen]=useState(false),[adding,setAdding]=useState<Song|null>(null),[busy,setBusy]=useState(false);const identity=useRef<string|null>(null),chain=useRef(Promise.resolve()),queued=useRef(0);
 const [libraryLoading,setLibraryLoading]=useState(false),[libraryReady,setLibraryReady]=useState(false);
 const epoch=useRef(0),authenticating=useRef(false),synced=useRef(false),libraryController=useRef<AbortController|null>(null),libraryTask=useRef<Promise<boolean>>(Promise.resolve(false));
 function guest():Library{try{return {...empty(),searches:updateSearches(JSON.parse(localStorage.getItem('resonance-searches-v1')||'[]'),'search-remove'),favorites:JSON.parse(localStorage.getItem('resonance-favorites-v2')||'[]'),recent:JSON.parse(localStorage.getItem('resonance-recent-v2')||'[]')}}catch{return empty()}}
 async function request(body?:unknown,signal?:AbortSignal,sessionOnly=false){return await accountRequest(body,signal,sessionOnly) as {error?:string;user:{id:string;name:string;username:string}|null;library?:Library;libraryPending?:boolean;libraryPatch?:Pick<Library,'recent'>|Pick<Library,'favorites'>|Pick<Library,'searches'>}}
 function loadLibrary(owner:string){
  libraryController.current?.abort();const controller=new AbortController(),generation=epoch.current;libraryController.current=controller;setLibraryLoading(true);setLibraryReady(false);synced.current=false;
  const task=request(undefined,controller.signal).then(d=>{if(controller.signal.aborted||epoch.current!==generation||identity.current!==owner)return false;if(d.user?.id!==owner||!d.library)throw Error('账号会话已变化，请刷新页面后重新登录。');setLibrary(d.library);synced.current=true;setLibraryReady(true);setError('');return true}).catch(()=>{if(!controller.signal.aborted&&epoch.current===generation&&identity.current===owner)setError('已登录，云端歌单暂时未能同步，请重试同步。');return false}).finally(()=>{if(libraryController.current===controller){setLibraryLoading(false);libraryController.current=null}});
  libraryTask.current=task;return task;
 }
 function reloadLibrary(){const owner=identity.current,generation=epoch.current;if(!owner||authenticating.current)return;setError('');void chain.current.catch(()=>{}).then(()=>{if(identity.current===owner&&epoch.current===generation)return loadLibrary(owner)})}
 function adopt(d:Awaited<ReturnType<typeof request>>){libraryController.current?.abort();libraryController.current=null;identity.current=d.user?.id||null;setUser(d.user);setLibraryLoading(false);if(d.user){setLibrary(d.library||empty());synced.current=!!d.library;setLibraryReady(!!d.library);if(d.library)libraryTask.current=Promise.resolve(true);else void loadLibrary(d.user.id)}else{synced.current=false;setLibraryReady(true);setLibrary(guest());libraryTask.current=Promise.resolve(false)}}
 useEffect(()=>{let live=true;const controller=new AbortController(),generation=epoch.current;request(undefined,controller.signal,true).then(d=>{if(live&&generation===epoch.current)adopt(d)}).catch(()=>{if(live&&generation===epoch.current){setLibrary(guest());setError('云端暂时无法连接，正在使用游客记录')}}).finally(()=>{if(live&&generation===epoch.current)setReady(true)});return()=>{live=false;controller.abort();libraryController.current?.abort();libraryController.current=null}},[]);
 function mutate(body:Record<string,unknown>){const owner=identity.current,generation=epoch.current;if(authenticating.current)return;if(!owner){setOpen(true);return}if(queued.current>=32){setError('操作较多，请等待当前同步完成');return}queued.current++;chain.current=chain.current.catch(()=>{}).then(async()=>{if(identity.current!==owner||epoch.current!==generation)return;try{if(!synced.current&&!await libraryTask.current)throw Error('歌单尚未完成同步，请先重试同步。');if(identity.current!==owner||epoch.current!==generation)return;const d=await request(body);if(identity.current===owner&&epoch.current===generation){if(d.library)setLibrary(d.library);else if(d.libraryPatch)setLibrary(previous=>({...previous,...d.libraryPatch}));setError('')}}catch(e){if(identity.current===owner&&epoch.current===generation)setError((e as Error).message)}}).finally(()=>{queued.current--})}
 function local(update:(d:Library)=>Library){setLibrary(d=>{const next=update(d);try{localStorage.setItem('resonance-searches-v1',JSON.stringify(next.searches));localStorage.setItem('resonance-favorites-v2',JSON.stringify(next.favorites));localStorage.setItem('resonance-recent-v2',JSON.stringify(next.recent))}catch{}return next})}
 function searchHistory(action:'search-save'|'search-remove'|'search-clear',query?:string){if(!ready)return;if(identity.current)mutate({action,query});else local(d=>({...d,searches:updateSearches(d.searches,action,query)}))}
 function like(song:Song){if(!ready)return;const saved=!library.favorites.some(s=>s.id===song.id&&s.provider===song.provider);if(identity.current)mutate({action:'favorite',song,saved});else local(d=>({...d,favorites:saved?[song,...d.favorites]:d.favorites.filter(s=>s.id!==song.id||s.provider!==song.provider)}))}
 function record(song:Song){if(!ready)return;if(identity.current)mutate({action:'history',song});else local(d=>({...d,recent:[song,...d.recent.filter(s=>s.id!==song.id||s.provider!==song.provider)].slice(0,200)}))}
 async function authenticate(body:unknown){if(authenticating.current)return;authenticating.current=true;setBusy(true);setError('');try{await chain.current;epoch.current++;libraryController.current?.abort();libraryController.current=null;setLibraryLoading(false);const d=await request(body);adopt(d);setReady(true);setOpen(false);setAdding(null)}catch(e){setError((e as Error).message);if(identity.current&&!synced.current)void loadLibrary(identity.current)}finally{authenticating.current=false;setBusy(false)}}
 function saveImport(body:Record<string,unknown>,onProgress?:(count:number)=>void){if(authenticating.current)return Promise.reject(Error('正在切换账号，请稍后再导入'));const owner=identity.current,generation=epoch.current;const task=chain.current.catch(()=>{}).then(async()=>{
 if(!owner||identity.current!==owner||epoch.current!==generation)throw Error('账号已变更，请重新导入');if(!synced.current&&!await libraryTask.current)throw Error('歌单尚未完成同步，请先重试同步。');
 const songs=body.songs as Song[];if(!Array.isArray(songs)||!songs.length)throw Error('没有可保存的歌曲');
 const controller=new AbortController(),last=Math.floor((songs.length-1)/50)*50;let next=0,completed=0;
 async function upload(offset:number){if(!owner||identity.current!==owner||epoch.current!==generation)throw Error('账号已变更，请重新导入');const batch=songs.slice(offset,offset+50),d=await request(importBatch(body,songs,offset),controller.signal);if(identity.current!==owner||epoch.current!==generation)throw Error('账号已变更，请重新导入');if(d.library)setLibrary(d.library);completed+=batch.length;onProgress?.(completed)}
 try{await Promise.all(Array.from({length:3},async()=>{while(next<last){const offset=next;next+=50;await upload(offset)}}));await upload(last)}catch(error){controller.abort();throw error}

 });chain.current=task.catch(()=>{});return task}

 useEffect(()=>{if(!user||!libraryReady||!library.playlists.some(p=>p.sync?.status==='pending'))return;const controller=new AbortController(),generation=epoch.current;let inFlight=false;const timer=setInterval(()=>{if(document.visibilityState!=='visible'||inFlight||authenticating.current)return;inFlight=true;request(undefined,controller.signal).then(d=>{if(!controller.signal.aborted&&generation===epoch.current&&identity.current===d.user?.id&&d.library)setLibrary(d.library)}).catch(()=>{}).finally(()=>{inFlight=false})},10000);return()=>{clearInterval(timer);controller.abort()}},[user?.id,libraryReady,library.playlists.some(p=>p.sync?.status==='pending')]);
 return {saveImport,user,library,libraryLoading,libraryReady,reloadLibrary,ready,error,setError,open,setOpen,adding,setAdding,busy,authenticate,mutate,like,record,searchHistory};}
export type Account=ReturnType<typeof useAccount>;
export function AccountDialog({account:a}:{account:Account}){const [register,setRegister]=useState(false),[captchaToken,setCaptchaToken]=useState(''),[captchaAttempt,setCaptchaAttempt]=useState(0);const needsChallenge=register?REGISTER_CHALLENGE_REQUIRED:LOGIN_CHALLENGE_REQUIRED;const dialog=useRef<HTMLDialogElement>(null);useEffect(()=>{if(a.open||a.adding)dialog.current?.showModal();else dialog.current?.close()},[a.open,a.adding]);return <dialog className="account-dialog" ref={dialog} onCancel={()=>{a.setOpen(false);a.setAdding(null)}}><button className="account-close" aria-label="关闭" onClick={()=>{a.setOpen(false);a.setAdding(null)}}>×</button>{a.adding&&a.user?<><h2>加入歌单</h2><p>{a.adding.title}</p>{a.library.playlists.map(p=><button className="account-choice" key={p.id} onClick={()=>{a.mutate({action:'add',id:p.id,song:a.adding});a.setAdding(null)}}>{p.name} · {p.songs.length} 首</button>)}{!a.libraryReady?<p>{a.libraryLoading?'正在同步歌单…':'歌单暂未同步，请先重试同步。'}</p>:!a.library.playlists.length&&<p>请先到「我的歌单」创建歌单。</p>}</>:a.user?<><h2>{a.user.name}</h2><p>@{a.user.username} · 云端记录已启用</p><button className="primary-btn" disabled={a.busy} onClick={()=>a.authenticate({action:'logout'})}>退出登录</button></>:<><h2>{register?'创建音乐账号':'欢迎回到共鸣'}</h2><p>收藏、歌单与聆听记录，随账号一起保存。</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);a.authenticate({action:register?'register':'login',username:f.get('username'),password:f.get('password'),name:f.get('name'),inviteCode:f.get('inviteCode'),turnstileToken:captchaToken}).finally(()=>{setCaptchaToken('');setCaptchaAttempt(v=>v+1)})}}>{register&&<label>昵称<input name="name" maxLength={40} autoComplete="nickname"/></label>}<label>账号<input required name="username" pattern="[a-zA-Z0-9_]{3,32}" placeholder="3–32 位字母、数字或下划线" autoComplete="username"/></label><label>密码<input required type="password" name="password" minLength={10} maxLength={128} placeholder="至少 10 位" autoComplete={register?'new-password':'current-password'}/></label><>{register&&<label>邀请码<input name="inviteCode" required maxLength={100} autoComplete="off" placeholder="请输入邀请码"/></label>}{a.open&&needsChallenge&&<TurnstileChallenge key={`${register}:${captchaAttempt}`} action={register?'register':'login'} onToken={setCaptchaToken}/>}</><button className="primary-btn" disabled={a.busy||!a.ready||(needsChallenge&&!captchaToken)}>{a.busy?'请稍候…':register?'注册并登录':'登录'}</button></form><button className="account-choice" onClick={()=>{setCaptchaToken('');setRegister(!register);a.setError('')}}>{register?'已有账号？去登录':'还没有账号？创建账号'}</button>{a.open&&<SsoButtons/>}</>}{a.error&&<p role="alert">{a.error}</p>}</dialog>}
export {PersonalPlaylists} from './personal-playlists';


